# Generated by Django 3.0.5 on 2020-05-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scancard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
