# Generated by Django 3.0.5 on 2020-05-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_scanner', '0002_auto_20200505_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='scancard',
            name='email',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AddField(
            model_name='scancard',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='UploadImages/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='scancard',
            name='mobile',
            field=models.CharField(default='Empty', max_length=200),
        ),
    ]
