# Generated by Django 3.0.5 on 2020-05-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_scanner', '0003_auto_20200506_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scancard',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scancard',
            name='mobile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
