# Generated by Django 3.0.5 on 2020-05-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_scanner', '0005_auto_20200507_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scancard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
